apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: 3000tcp
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: api.addysnip
  sessionAffinity: None