apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api.addysnip
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api.addysnip
    spec:
      containers:
      - command:
        - /app/app
        - -v
        - server
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: {{ default "0" .Values.api.grpc.log.verbosity }}
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: {{ default "error" .Values.api.grpc.log.severity }}
        envFrom:
        - secretRef:
            name: api
            optional: false
        - secretRef:
            name: database
            optional: false
        - secretRef:
            name: rabbitmq
            optional: false
        - secretRef:
            name: redis
            optional: false
        {{- with .Values.api.image }}
        image: "{{- if .repository -}}{{ .repository }}{ else }}{{ .registry }}/{{ .image }}{{- end -}}:{{ .tag }}{{- if (.digest) -}}@{{ .digest }}{{- end -}}"
        {{- end }}
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 3000
          name: 3000tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30