apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: 5000tcp
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: billing.addysnip
  sessionAffinity: None