apiVersion: v1
kind: Secret
metadata:
  name: smtp-noreply
  namespace: {{ .Release.Namespace }}
stringData:
  SMTP_HOST: {{ default "localhost" .Values.config.smtp.host }}
  SMTP_PORT: {{ default "25" .Values.config.smtp.port }}
  SMTP_USER: {{ default "root" .Values.config.smtp.user }}
  SMTP_PASS: {{ default "secret" .Values.config.smtp.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
stringData:
  RABBITMQ_HOST: {{ .Values.config.rabbitmq.host }}
  RABBITMQ_PORT: {{ .Values.config.rabbitmq.port }}
  RABBITMQ_USER: {{ .Values.config.rabbitmq.user }}
  RABBITMQ_PASSWORD: {{ .Values.config.rabbitmq.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: {{ .Release.Namespace }}
stringData:
  DATABASE_CA_CERT: {{ .Values.config.database.caCert }}
  DATABASE_DSN: {{ .Values.config.database.dsn }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
stringData:
  REDIS_HOST: {{ .Values.config.redis.host }}
  REDIS_PORT: {{ .Values.config.redis.port }}
  REDIS_PASSWORD: {{ .Values.config.redis.password }}
  REDIS_SENTINEL: {{ .Values.config.redis.sentinel.enabled }}
  REDIS_SENTINEL_ADDR: {{ .Values.config.redis.sentinel.addr }}
---
apiVersion: v1
kind: Secret
metadata:
  name: billing
  namespace: {{ .Release.Namespace }}
stringData:
  APP_URL: {{ .Values.billing.appUrl }}
  GRPC_CERT: {{ .Values.billing.grpc.cert }}
  GRPC_KEY: {{ .Values.billing.grpc.key }}
  GRPC_PORT: {{ .Values.billing.grpc.port }}
  GRPC_TOKEN: {{ .Values.billing.grpc.token }}
  RABBITMQ_QUEUE: {{ default "emailer" .Values.billing.rabbitmq.queue }}
  STRIPE_KEY: {{ .Values.billing.stripe.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
stringData:
  GRPC_BILLING_CACERT: {{ .Values.api.grpc.billing.caCert }}
  GRPC_BILLING_HOST: {{ .Values.api.grpc.billing.addr }}
  GRPC_BILLING_TOKEN: {{ .Values.api.grpc.billing.token }}
  JWT_SECRET: {{ .Values.api.jwtSecret }}
  SESSION_SECRET: {{ .Values.api.sessionSecret }}
  RABBITMQ_QUEUE_EMAILER: {{ default "emailer" .Values.emailer.rabbitmq.queue }}
  RABBITMQ_QUEUE_BILLING: {{ default "billing" .Values.billing.rabbitmq.queue }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson | b64enc }}